dist: jammy
language: python
sudo: false
python:
- '3.8'
install:
- pip install -r requirements.txt
- pip install coverage
- pip install flake8 pytest PyYAML
- pip install coveralls
- pip install setuptools --upgrade
script:
- flake8 ./ || travis_terminate 1;
- python setup.py test || travis_terminate 1;
after_success:
- coveralls --rcfile=.coveragerc
- "./deploy-staging.sh"
notifications:
  email:
    on_success: change
    on_failure: always
    slack: cloudcv:gy3CGQGNXLwXOqVyzXGZfdea
deploy:
  provider: pypi
  user: cloudcv
  password:
    secure: RiELCr5IMQayDlvwkHh18spa/20xO3T5a8XCEr/ZrY27AygTaFICR8zjKVdbPXRfn/uPtgRRlKJaIdQLpmHnDjmGbNNQo8Ga5E3N89sPcGjHSM7PKPcwSUu8Gwgk70YjXEnos/Bz4u/12kJ2UrgQZHlPpl0ySZRFjk8sqxwQbcxqM8lO1Wu+lGvuCufzllLDcC/Fz1OQjuXUuete/W1RHtDZD8khnKBa5p9P6c0H6AZI9+uvzCsA9qeWFqIiU9TuLja4jb9EcZdtXDDdKTbSHvft6/4JqzQBbsk5x31q5qjG8JFxh7DBrKSv3KXn5XQ7vXQOC7q4RJYDcxFrDBH3hrbO/wkRh/1qHcjzlACGQAUzECnmh+dkr1u9gnUdkC1ti78jkiC4ICA3YfCm9VDYUPSYfOgIXj2Fbv5FfJnggItO+8CLI/vnsu5MqSp/fmrjugO++lo3BC/b6/gonkt3HvyfX2DN7yMG0OMPpr2/5o+NDJekcpKg5VLAv7y3/I8hSj2LMIJ8zV9oAJAxA/qAPuOupxBTjn1+GeiR8Erx7Jak4BRm426JtvICU4h5Zn+d6Vcr1q12OwcZrOUJiBsFhfZebgUmctZjDtsJQwtysF7fovVsT6pXrTGLFgxgkxzXdn/+pyC9bwdKEdw+vbdEjxGasRtijS9BIa676ZFMRsM=
  distributions: sdist bdist_wheel
  on:
    tags: true
